---
resources:
  - namespaces.yaml

helmCharts:
  # - name: otel-collector
  #   includeCRDs: true
  #   releaseName: otel-collector
  #   valuesFile: values.yaml

  # - name: distributed-tracing-ui-plugin
  #   includeCRDs: true
  #   releaseName: distributed-tracing-ui-plugin
  #   valuesFile: values.yaml

  - name: grafana
    includeCRDs: true
    releaseName: grafana
    valuesFile: values.yaml
    repo:  # we expand chart in folder

  - name: uwm
    includeCRDs: true
    releaseName: uwm
    valuesFile: values.yaml
    repo:  # we expand chart in folder
