# list of operators
operators:
  # openshift cluster observability
  - name: cluster-observability-operator
    namespace:
      name: openshift-cluster-observability-operator
      create: true
      global: true
    channels: [stable] # v0,1
    version: "1.3.0" # v1
    catalog: openshift-redhat-operators #v1
    source: redhat-operators # v0
    sourceNamespace: openshift-marketplace # v0
    enabled: true

  # grafana
  - name: grafana-operator
    namespace:
      name: openshift-grafana-operator
      create: true
      global: true
    channels: [v5] # v0,1
    version: "5.20.0" # v1
    catalog: community-operators #v1
    source: redhat-operators # v0
    sourceNamespace: openshift-marketplace # v0
    enabled: true

  # otel
  - name: opentelemetry-product
    namespace:
      name: openshift-opentelemetry-operator
      create: true
      global: true
    channels: [stable] # v0,1
    version: "0.135.0-1" # v1
    catalog: openshift-redhat-operators #v1
    source: redhat-operators # v0
    sourceNamespace: openshift-marketplace # v0
    enabled: true

  # tempo
  - name: tempo-product
    namespace:
      name: openshift-tempo-operator
      create: true
      global: true
    channels: [stable] # v0,1
    version: "0.18.0-2" # v1
    catalog: openshift-redhat-operators #v1
    source: redhat-operators # v0
    sourceNamespace: openshift-marketplace # v0
    enabled: true
