clusterPoolName: roadshow  # name of this cluster pool
imageSetRef: img4.20.8-x86-64-appsub  # openshift spoke cluster version
region: us-east-2  # region
runningCount: 0  # keep one cluster running rather than hibernate it
size: 0  # number of spoke clusters
baseDomain:
installConfigSecretTemplateRef: roadshow-install-config-template  # ConfigMap for install-config
globalPullSecret:
installConfig:
sshKey:
