---
resources:
  - ../../base
  # - distributed-workloads.yaml # rhoai3 creates default queues and flavors
  - namespace.yaml
  - llama-cpp-runtime-template.yaml
  - model-catalog-unmanaged-sources.yaml
  - hardware-profile.yaml
  - leader-worker-set.yaml
  - kuadrant-cr.yaml
  - authorino-cr.yaml
  - mcp-configmap.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: dsci-cr.yaml
  - path: dsc-cr.yaml
  - path: odh-dashboard.yaml
