---
apiVersion: v1
data:
  tavily-search-api-key: '{{ `{{hub fromSecret "openshift-gitops" "tavily-search-key" "tavily-search-api-key" hub}}` }}'
kind: Secret
metadata:
  name: tavily-search-key
type: Opaque
