---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: check-install
  name: check-install
  namespace: openshift-config
---
apiVersion: batch/v1
kind: Job
metadata:
  name: check-install
  namespace: openshift-config
spec:
  backoffLimit: 50
  activeDeadlineSeconds: 3600
  template:
    metadata:
      name: check-install
    spec:
      containers:
      - name: check-install
        image: 'quay.io/eformat/toolbox:latest'
        command:
        - /bin/sh
        - '-x'
        - /tmp/check-install/check-install.sh
        resources: {}
        volumeMounts:
        - name: check-install
          mountPath: /tmp/check-install
        - mountPath: /tmp
          name: cert-tmp
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
      serviceAccount: check-install
      serviceAccountName: check-install
      securityContext: {}
      restartPolicy: OnFailure
      volumes:
      - name: check-install
        configMap:
          items:
          - key: check-install.sh
            mode: 509
            path: check-install.sh
          name: check-install
      - emptyDir: {}
        name: cert-tmp
      dnsPolicy: ClusterFirst
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: check-install
rules:
  - apiGroups: ["config.openshift.io"]
    resources: ["ingresses", "dnses", "apiservers", "ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["config.openshift.io"]
    resources: ["clusteroperators"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["applications", "applicationsets"]
    verbs: ["get", "list", "watch", "patch", "create", "delete"]
  - apiGroups: ["machineconfiguration.openshift.io"]
    resources: ["kubeletconfigs"]
    verbs: ["get", "list", "watch", "patch", "create", "delete"]
  - apiGroups: [""]
    resources: ["jobs", "daemonsets", "pods", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["serving.kserve.io"]
    resources: ["inferenceservices"]
    verbs: ["get", "list", "watch", "patch", "create", "delete"]
  - apiGroups: ["kueue.x-k8s.io"]
    resources: ["clusterqueues"]
    verbs: ["get", "list", "watch", "patch", "create", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: check-install
subjects:
  - kind: ServiceAccount
    name: check-install
    namespace: openshift-config
roleRef:
  kind: ClusterRole
  name: check-install
  apiGroup: rbac.authorization.k8s.io
