---
resources:
  - policy-operators.yaml
  - policy-argocd.yaml
  - policy-vault.yaml
  - policy-gpu-node-label.yaml
  - policy-gateway.yaml
  - policy-aws-creds.yaml
  - policy-cluster-autoscaler.yaml
  - policy-storage-quota.yaml
