apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - subscription.yaml

helmGlobals:
  chartHome: ../../helm

helmCharts:
  - name: web-terminal
    includeCRDs: true
    releaseName: web-terminal
    valuesFile: values.yaml
