---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: vault-init
  name: vault-init
  namespace: vault
---
apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  namespace: vault
spec:
  backoffLimit: 50
  activeDeadlineSeconds: 1200
  template:
    metadata:
      name: vault-init
    spec:
      containers:
      - name: vault-init
        image: 'quay.io/eformat/toolbox:latest'
        command:
        - /bin/sh
        - '-x'
        - /tmp/vault-config/vault-setup.sh
        resources: {}
        volumeMounts:
        - name: vault-init
          mountPath: /tmp/secrets
        - name: vault-config
          mountPath: /tmp/vault-config
        - mountPath: /tmp
          name: vault-tmp
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
      serviceAccount: vault-init
      serviceAccountName: vault-init
      securityContext: {}
      restartPolicy: OnFailure
      volumes:
      - name: vault-init
        secret:
          secretName: vault-init
          defaultMode: 420
      - name: vault-config
        configMap:
          items:
          - key: vault-setup.sh
            mode: 509
            path: vault-setup.sh
          name: vault-init
      - emptyDir: {}
        name: vault-tmp
      dnsPolicy: ClusterFirst
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-init
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "secrets"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: ["config.openshift.io"]
    resources: ["ingresses", "dnses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["project.openshift.io"]
    resources: ["projects"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings", "roles"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-init
subjects:
  - kind: ServiceAccount
    name: vault-init
    namespace: vault
roleRef:
  kind: ClusterRole
  name: vault-init
  apiGroup: rbac.authorization.k8s.io
