---
apiVersion: hive.openshift.io/v1
kind: ClusterPool
metadata:
  name: {{ .Values.clusterPoolName }}-{{ .Values.guid }}
  namespace: cluster-pools
spec:
  baseDomain: {{ .Values.baseDomain }}
  imageSetRef:
    name: {{ .Values.imageSetRef }}
  installConfigSecretTemplateRef: 
    name: {{ .Values.installConfigSecretTemplateRef }}-{{ .Values.guid }}
  skipMachinePools: true
  runningCount: {{ .Values.runningCount }}
  platform:
    aws:
      credentialsSecretRef:
        name: aws-creds-{{ .Values.guid }}
      region: {{ .Values.region }}
  size: {{ .Values.size }}
