---
apiVersion: v1
stringData:
  install-config.yaml: {{ .Values.installConfig | toYaml | indent 2 }}
kind: Secret
metadata:
  name: roadshow-install-config-template-{{ .Values.guid }}
  namespace: cluster-pools
type: Opaque
