---
apiVersion: v1
stringData:
  aws_access_key_id: {{ .Values.aws_access_key_id }}
  aws_secret_access_key: {{ .Values.aws_secret_access_key }}
kind: Secret
metadata:
  annotations:
    cloudcredential.openshift.io/mode: mint
  name: aws-creds-{{ .Values.guid }}
  namespace: cluster-pools
type: Opaque
