---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: mcp-github
placementBindingDefaults:
  name: mcp-github
policyDefaults:
  placement:
    placementName: placement-spokes-openshift
  categories:
    - CM Configuration Management
  complianceType: "musthave"
  controls:
    - CM-2 Baseline Configuration
  consolidateManifests: false
  copyPolicyMetadata: false
  disabled: false
  namespace: openshift-gitops
  pruneObjectBehavior: "None"
  remediationAction: enforce
  severity: medium
  standards:
    - NIST SP 800-53
  policyAnnotations: {"argocd.argoproj.io/compare-options": "IgnoreExtraneous"}
policies:
  - name: mcp-github-sno
    manifests:
      - path: sno/
  - name: mcp-github-eso
    disabled: false
    pruneObjectBehavior: "DeleteAll"
    placement:
      placementName: placement-hub-openshift
    manifests:
      - path: eso/
