---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gpu
placementBindingDefaults:
  name: gpu
policyDefaults:
  placement:
    placementName: placement-spokes-openshift
  categories:
    - CM Configuration Management
  complianceType: "musthave"
  configurationPolicyAnnotations: {"policy.open-cluster-management.io/disable-templates": "true"}
  controls:
    - CM-2 Baseline Configuration
  consolidateManifests: false
  copyPolicyMetadata: false
  disabled: false
  namespace: openshift-gitops
  pruneObjectBehavior: "None"
  remediationAction: enforce
  severity: medium
  standards:
    - NIST SP 800-53
  policyAnnotations: {"argocd.argoproj.io/compare-options": "IgnoreExtraneous"}
policies:
  - name: gpu
    manifests:
      - path: sno/
