---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: cert-init
  name: cert-init
  namespace: openshift-config
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cert-init
  namespace: openshift-config
spec:
  backoffLimit: 20
  activeDeadlineSeconds: 1800
  template:
    metadata:
      name: cert-init
    spec:
      containers:
      - name: cert-init
        image: 'quay.io/eformat/toolbox:latest'
        env:
        - name: EMAIL
          value: {{ .Values.email }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.aws_default_region }}
        {{- if .Values.acme_staging }}
        - name: ACME_STAGING
          value: "True"
        {{- end }}
        command:
        - /bin/sh
        - '-x'
        - /tmp/cert-config/certificates.sh
        resources: {}
        volumeMounts:
        - name: cert-config
          mountPath: /tmp/cert-config
        - mountPath: /tmp
          name: cert-tmp
        - name: route53-hostedzone
          mountPath: /tmp/secrets
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
      serviceAccount: cert-init
      serviceAccountName: cert-init
      securityContext: {}
      restartPolicy: OnFailure
      volumes:
      - name: route53-hostedzone
        secret:
          secretName: route53-hostedzone
          defaultMode: 420
      - name: cert-config
        configMap:
          items:
          - key: certificates.sh
            mode: 509
            path: certificates.sh
          name: cert-init
      - emptyDir: {}
        name: cert-tmp
      dnsPolicy: ClusterFirst
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-init
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "secrets"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: ["config.openshift.io"]
    resources: ["ingresses", "dnses", "apiservers", "ingresses"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["project.openshift.io"]
    resources: ["projects"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings", "roles"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates", "issuers", "clusterissuers"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: ["operator.openshift.io"]
    resources: ["certmanagers", "ingresscontrollers"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-init
subjects:
  - kind: ServiceAccount
    name: cert-init
    namespace: openshift-config
roleRef:
  kind: ClusterRole
  name: cert-init
  apiGroup: rbac.authorization.k8s.io
