---
resources:
  - namespace.yaml
  - service-account.yaml
  - rbac.yaml
  - service.yaml
  - deployment.yaml
  - tiers-to-group-config-map.yaml
  - service-monitor.yaml
  - auth-policy.yaml
  - http-route.yaml
  - rate-limit-policy.yaml
  - telemetry.yaml
