apiVersion: v1
baseDomain: $GUID-prelude.$BASE_DOMAIN
compute:
- name: worker
  hyperthreading: Enabled
  replicas: 0
controlPlane:
  name: master
  replicas: 1
  architecture: amd64
  hyperthreading: Enabled
  platform:
    aws:
      type: $INSTANCE_TYPE
      rootVolume:
        size: $ROOT_VOLUME_SIZE
        type: gp3
metadata:
  name: hivec
platform:
  aws:
    region: $AWS_DEFAULT_REGION
    userTags:
      owner: $USER_EMAIL
      team: $USER_TEAM
      usage: $USER_USAGE
      description: $USER_USAGE_DESCRIPTION
sshKey: $SSH_PUBLIC_KEY
